- name: Import steps to configure new USB storage
  include_tasks: storage.yml

- name: Import steps to configure networking
  include_tasks: network.yml

- name: Import steps to install and update necessary packages
  include_tasks: packages.yml

- name: Import master-setup if machine is a master
  include_tasks: master-setup.yml
  when: ansible_nodename in groups['master']
