- name: Configure bucket to use with helm deployments
  import_tasks: bucket-config
  tags: bucket-config
  
- name: Import helm cert-manager terraform deployment
  import_tasks: helm-cert-manager.yml
  tags: 
    - network
    - helm-cert-manager

- name: Import helm contour terraform deployment
  import_tasks: helm-contour.yml
  tags:
    - network
    - helm-contour

- name: Import MetalLB terraform deployment
  import_tasks: helm-metallb.yml
  when: build == 'pi'
  tags:
    - network
    - helm-metallb

- name: Import Rook-Ceph steps
  import_tasks: helm-rook-ceph.yml
  tags:
    - storage
    - helm-rook-ceph

- name: Import Harbor steps
  import_tasks: helm-harbor.yml
  when: build == 'pi'
  tags:
    - registry
    - helm-harbor