- name: Move vars template to main folder
  template:
    src: templates/terraform.tfvars.j2
    dest: /environments/cloud/kubernetes/terraform.tfvars

- name: Move terraform files to main folder
  copy:
    src: files/k3s-aws/
    dest: /environments/cloud/kubernetes 
    
- name: Import terraform role and run tasks associated with it 
  import_role:
    name: terraform
    tasks_from: main