- name: Include AWS credentials to allow creation of s3 bucket for Terraform state
  include_vars:
    file: vars/aws/k3s-creds.yml

- name: Include variables for terraform so it can access DigitalOcean
  include_vars:
    dir: 'vars/do'
  when: build == 'do'

- name: Import steps for terraform state bucket configuration
  import_tasks: bucket-config.yml

- name: Set terraform build folder
  set_fact:
    terraform_build_folder: "files/k3s-{{ build }}/"

- name: Import terraform pre steps
  import_tasks: pre.yml

- name: Copy over the s3 backend configuration file
  template:
    src: templates/s3-backend/s3-backend.tf.j2
    dest: $HOME/terraform/s3-backend.tf

- name: Move terraform files to main folder
  template:
    src: "{{ terraform_build_folder }}"
    dest: $HOME/terraform

- name: Import main terraform steps
  import_tasks: build.yml
  vars:
    tf_plan_name: "{{ build }}-k3s-cluster"
    workspace: "{{ build }}-k3s-cluster"

- name: Get master ip's
  shell: terraform output | grep m | awk '{ print $3 }'
  register: master_ips

- name: Get worker ip's
  shell: terraform output | grep w | awk '{ print $3 }'
  register: worker_ips

- name: Add master ips to in memory inventory
  add_host:
    name: "{{ item }}"
    group: master
  with_items: "{{ master_ips.stdout_lines }}"

- name: Add worker ips to in memory inventory
  add_host:
    name: "{{ item }}"
    group: workers
  with_items: "{{ worker_ips.stdout_lines }}"

- pause:
      seconds: 15
    
- name: Import post steps for terraform
  import_tasks: post.yml