- name: Import steps for terraform state bucket configuration
  import_tasks: bucket-config.yml

- name: Set terraform build folder
  set_fact:
    terraform_build_folder: "files/k3s-{{ build }}/"

- name: Check if k3s ssh key pair exists
  stat:
    path: "~/.ssh/k3s-{{ build }}"
  register: ssh_keypair_status

- name: Generate ssh key pair for k3s if it doesn't exist
  block:
    - name: Create SSH folder
      file:
        path: ~/.ssh
        state: directory
    - name: Generate ssh keypair
      openssh_keypair:
        path: "~/.ssh/k3s_{{ build }}"
  when: ssh_keypair_status.stat.exists == False

- name: Import terraform pre steps
  import_tasks: pre.yml

- name: Copy over the s3 backend configuration file
  template:
    src: templates/s3-backend/s3-backend.tf.j2
    dest: $HOME/terraform/s3-backend.tf
  vars:
    workspace: "k3s-{{ build }}-cluster"

- name: Move terraform files to main folder
  copy:
    src: "{{ terraform_build_folder }}"
    dest: $HOME/terraform

- name: Import main terraform steps
  import_tasks: build.yml
  vars:
    tf_plan_name: "k3s-{{ build }}-cluster"
    workspace: "k3s-{{ build }}-cluster"

- name: Get master ip's
  shell: terraform output | grep k3s-{{ build }}-m | awk -F ':' ' {print $2 }' | tr -d '",'
  register: master_ips

# - name: Get worker ip's
#   shell: terraform output | grep k3s-{{ build }}-w | awk -F ':' ' {print $2 }' | tr -d '",'
#   register: worker_ips

- name: Add master ips to in memory inventory
  add_host:
    name: "{{ item }}"
    group: masters
  with_items: "{{ master_ips.stdout_lines }}"

# - name: Add worker ips to in memory inventory
#   add_host:
#     name: "{{ item }}"
#     group: workers
#   with_items: "{{ worker_ips.stdout_lines }}"

- pause:
      seconds: 15
    
- name: Import post steps for terraform
  import_tasks: post.yml
