- name: Import k3s terraform steps
  import_tasks: k3s.yml
  when: cluster_type == 'k3s'
  tags: k3s_build

- name: Import kops terraform steps
  import_tasks: kops.yml
  when: cluster_type == 'kops'
  tags: kops_build