kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-registry
provisioner: rancher.io/longhorn
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
  recurringJobs: '[{"name":"snap", "task":"snapshot", "cron":"0 1 * * *", "retain":1},
                   {"name":"backup", "task":"backup", "cron":"0 3 * * *", "retain":1}]'