- name: Cloud - Install k3s, make master unschedulable, and do not deploy traefik
  shell: curl -sfL https://get.k3s.io | sh -s - server --node-taint key1=value1:NoExecute --no-deploy=traefik
  when: build == 'aws' or build == 'do'

- name: Bare Metal (PI) - Install k3s and do not deploy traefik
  shell: curl -sfL https://get.k3s.io | sh -s - server --no-deploy=traefik
  when: build == 'pi'

- name: Add non-root user as owner of Rancher k3s config
  file:
    path: /etc/rancher/k3s/k3s.yaml
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Export token to be used with worker bootstrap
  shell: cat /var/lib/rancher/k3s/server/node-token
  register: master_token
  become: yes

- name: Export master ip addr for boostrapping worker nodes
  shell: hostname -I | awk '{ print $1 }'
  register: master_ip

- name: Create holder for token and ip so it can be applied to the workers
  add_host:
    name: "MasterCreds"
    m_token: "{{ master_token.stdout }}"
    m_ip: "{{ master_ip.stdout }}"
