- hosts: localhost
  tasks:
    - name: Import Terraform deployment
      import_role:
        name: ../roles/terraform
        tasks_from: k3s
      when: build == 'do' or build == 'aws'

- hosts: master
  remote_user: "{{ user }}"
  become: yes
  tasks:

    - name: Import master initialization steps
      import_role:
        name: ../roles/k3s
        tasks_from: master-init

- hosts: workers
  serial: 1
  remote_user: "{{ user }}"
  become: yes
  vars:
    m_token: "{{ hostvars['MasterCreds']['m_token'] }}"
    m_ip: "{{ hostvars['MasterCreds']['m_ip'] }}"
  tasks:

    - name: Import worker initialization steps
      import_role:
        name: ../roles/k3s
        tasks_from: worker-init

- hosts: localhost
  tasks:

    - name: Include variables for k3s items
      include_vars:
        dir: vars/k3s

    - name: Copy kubeconfig from master to host
      fetch:
        src: /var/lib/rancher/k3s/agent/kubeconfig.yaml
        dest: /home/devel/.kube/config
      delegate_to: "{{ groups['master'] | random }}"
  
    - name: Import master post install steps
      import_role:
        name: ../roles/k3s
        tasks_from: master-post