- name: Install Common components
  shell: kubectl apply -f https://raw.githubusercontent.com/rook/rook/blob/release-1.2/cluster/examples/kubernetes/ceph/common.yaml

- name: Install Operator
  shell: kubectl apply -f https://raw.githubusercontent.com/rook/rook/release-1.2/cluster/examples/kubernetes/ceph/operator.yaml

- name: Create Ceph cluster
  shell: "kubectl apply -f {{ build_file }}"

- name: Create block storage class
  k8s:
    state: present
    definition: "{{ lookup('file', 'files/blockstorageclass.yml') }}"
    validate:
      fail_on_error: yes

# - name: Create s3 storage class
#   k8s:
#     state: present
#     definition: "{{ lookup('file', 'files/s3storageclass.yml') }}"
#     validate:
#       fail_on_error: yes