- name: Import varaibles for all k3s builds
  include_vars:
    dir: vars/k3s/main

- name: Import variables for pi build
  include_vars:
    dir: vars/k3s/pi
  when: build == 'pi'

- name: Import variables for Digital Ocean build
  block:
    - include_vars:
        dir: vars/do
    - include_vars:
        dir: vars/user
  when: build == 'do'

- name: Import variables for AWS build
  include_vars:
    dir: vars/k3s/aws
  when: build == 'aws'
