apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: rook-ceph-mgr-dashboard
  namespace: rook-ceph
spec:
  virtualhost:
    fdqn: ceph-dash.chaseweyer.com
    tls:
      secretName: cf-le-prod
  routes:
    - match: /
      services:
        - name: rook-ceph-mgr-dashboard
          port: https-dashboard