- name: Import instance variables
  include_vars:
    dir: 'vars/aws'

- name: Ensure ~/.aws directory exists for AWS configuration
  file: 
    path: ~/.aws 
    state: directory

- name: Add template config file to ~/.aws directory
  template:
    src: config
    dest: ~/.aws/config

- name: Add template credentials file to ~/.aws directory
  template:
    src: credentials
    dest: ~/.aws/credentials

- name: Create AWS ec2 instance
  ec2:
    key_name: "{{ keypair }}"
    group_id: "{{ sg_id }}"
    vpc_subnet_id: "{{ sb_id }}"
    assign_public_ip: yes
    instance_type: "{{ instance_type }}"
    image: "{{ image_id }}"
    wait: yes
    wait_timeout: 500
    volumes:
      - device_name: "{{ device_name }}"
        volume_type: "{{ volume_type }}"
        volume_size: "{{ volume_size }}"
        delete_on_termination: true
    count: "{{ count }}"
    region: "{{ region }}"
  register: ec2

- name: Show output from AWS Instance Creation
  debug: 
    msg: "{{ ec2 }}"

- name: Setting reusable variable for EC2 instance
  set_fact:
    new_machine: "{{ ec2.instances }}"

- name: Add name tag to instance
  ec2_tag:
    resource: "{{ item.id }}" 
    region: "{{ region }}" 
    state: "present"
  with_items: "{{ new_machine }}"
  args:
    tags:
      Name: "{{ name }}"
  no_log: True

- name: Wait for SSH to be available
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22 
    state: started
    timeout: 500
  with_items: "{{ new_machine }}"
  no_log: True

- name: Make user identifying script executable
  file:
    path: ./roles/aws/files/generate-user.sh
    mode: '0755'

- name: Generating user based on image flavor used
  shell: ./roles/aws/files/generate-user.sh {{ item.id }}
  register: new_user
  with_items: "{{ new_machine }}"
  no_log: True

- name: Set user variable
  set_fact:
    user: "{{ item.stdout }}"
  with_items: "{{ new_user.results }}"

- name: Set keypair name to be used for ssh
  set_fact:
    full_keypair: "{{ keypair }}.pem"

- name: Display connection steps
  debug:
    msg: 
      - "Your Public DNS is {{ item.public_dns_name }}"
      - "You can access your new instance as follows:"
      - "ssh -i {{ full_keypair }} {{ user }}@{{ item.public_dns_name }}"
      - "Replace the path to the ssh key as needed so that it points to the correct folder."
      - "If the user value listed does not work, try using *root* instead."
  with_items: "{{ new_machine }}"
  loop_control:
   label: "{{ item.public_dns_name }}"

- name: Remove AWS configuration and credentials
  file:
    state: absent
    path: ~/.aws
   