#!/bin/bash

###########################################################
#
# Program name: deploy-application.sh
#
# Author: Chase Weyer
#
# This script is used to automatically deploy an application
# on to the GKE platform for the first time. It will read in
# an application file name from the main json configuration 
# and deploy it on the Kubernetes network generated by GKE.
#
############################################################

# Get environment variables
function environment-variables {
    APPLICATION=$(cat ../gcp.json | jq .'application');
    AUTH=$(echo "$APPLICATION" | jq -r '.auth');
    ENVIRONMENT=$(cat ../gcp.json | jq .'environment');
    PROJECT_NAME=$(echo "$ENVIRONMENT" | jq -r '.projectname');
    CLUSTER_NAME=$(echo "$ENVIRONMENT" | jq -r '.clustername');
    ZONE_NAME=$(echo "$ENVIRONMENT" | jq -r '.zone');
}
# Login with app deployer service account
function login {
    gcloud auth activate-service-account --key-file=$AUTH
}

function enable-kubectl {

    # Grab cluster credentials to enable kubectl
    echo "** Enable kubectl to work with cluster **"
    gcloud container clusters get-credentials \
    $CLUSTER_NAME \
    --zone $ZONE_NAME \
    --project $PROJECT_NAME
}

# Deploy application based on value passed in
function deploy {

    echo "** Deploying application **"
    kubectl create -f ../../shared/kubernetes/deployment/professional-site/professional-site.yaml
}

# Exit program if any of the steps fail
set -e

# Enable steps in this order:
# Set up Environment Variables
# Login
# Deploy application

environment-variables
login
enable-kubectl
deploy

