- hosts: master
  remote_user: pi
  become: yes
  tasks:
  - name: Import variables for k3s pi master build
    include_vars:
      file: vars/user/pi.yml

  - name: Install k3s on master with non-scheduable masters and no traefik
    shell: curl -sfL https://get.k3s.io | sh -s - server --no-deploy=traefik

  - name: Initiate k3s pi master build
    import_role:
      name: k3s
      tasks_from: master-init

- hosts: workers
  serial: 1
  remote_user: pi
  become: yes
  vars:
    m_token: "{{ hostvars['MasterCreds']['m_token'] }}"
    m_ip: "{{ hostvars['MasterCreds']['m_ip'] }}"
  tasks:
    
    - name: Import worker initialization steps
      import_role: k3s
      tasks_from: worker-init

- hosts: localhost
  remote_user: devel
  tasks:
  - name: Include variables for k3s items
    include_vars:
      dir: vars/k3s
      
  - name: Copy kubeconfig from master to host
    fetch:
      src: /var/lib/rancher/k3s/agent/kubeconfig.yaml
      dest: /home/devel/.kube/config
    delegate_to: master

  - name: Run Post install checkers on master
    import_role:
      name: k3s
      tasks_from: master-post

  - name: Install infrastructure for Pi build (Ingress & LB)
    import_role:
      name: k3s
      tasks_from: infra-pi

  - name: Install Cert Manager
    import_role:
      name: cert-manager

  - name: Install Ceph
    import_role:
      name: ceph
    vars:
      build_file: files/ceph-cluster-pi.yml