- hosts: localhost
  tasks:
    - name: Import vars for aws-ec2 builds
      include_vars:
        dir: vars/aws-ec2

    - name: Import k3s aws deployment
      import_role:
        name: terraform
        tasks_from: k3s-aws

- hosts: master
  remote_user: "{{ user }}"
  become: yes
  tasks:

    - name: Install k3s and make master unschedulable
      shell: curl -sfL https://get.k3s.io | sh -s - server --node-taint key1=value1:NoExecute

    - name: Import master initialization steps
      import_role:
        name: k3s
        tasks_from: master-init

- hosts: workers
  serial: 1
  remote_user: "{{ user }}"
  become: yes
  vars:
    m_token: "{{ hostvars['MasterCreds']['m_token'] }}"
    m_ip: "{{ hostvars['MasterCreds']['m_ip'] }}"
  tasks:

    - name: Import worker initialization steps
      import_role:
        name: k3s
        tasks_from: worker-init

- hosts: localhost
  remote_user: "{{ user }}"
  tasks:

    - name: Include variables for k3s items
      include_vars:
        dir: vars/k3s

    - name: Copy kubeconfig from master to host
      fetch:
        src: /var/lib/rancher/k3s/agent/kubeconfig.yaml
        dest: /home/devel/.kube/config
      delegate_to: master
  
    - name: Import master post install steps
      import_role:
        name: k3s
        tasks_from: master-post

    - name: Import cert-manager install steps
      import_role:
        name: cert-manager

    - name: Import ceph install steps
      import_role:
        name: ceph
      vars:
        build_file: templates/ceph-cluster-aws.yml