first_master_wifi_static_ip: 192.168.0.40
first_worker_wifi_static_ip: 192.168.0.41
second_worker_wifi_static_ip: 192.168.0.42
first_master_eth_static_ip: 192.168.0.20
first_worker_eth_static_ip: 192.168.0.21
second_worker_eth_static_ip: 192.168.0.22
